# Generated by Django 2.1.5 on 2019-01-17 03:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=4000, null=True)),
                ('location', models.CharField(max_length=50)),
                ('par', models.IntegerField()),
                ('yardage', models.CharField(max_length=140)),
                ('img', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dogfight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='2019-01-19')),
                ('start_time', models.TimeField(default=datetime.time(7, 30))),
                ('number_of_groups', models.IntegerField(default=5)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dogfight_course', to='feed.Course')),
            ],
        ),
    ]
